### ISSUE TITLE
Run zone guarded?

### ISSUE THREAD

**Issue by markst** [lsaudon/appcenter_sdk_flutter#5]
Would it be right to run my app in a zone and track exception stack trace like so?

```dart
void main() async {
  runZonedGuarded<Future<void>>(() async {
    final binding = WidgetsFlutterBinding.ensureInitialized();
    AppCenter.start(secret: "");
    FlutterError.onError = (final details) async {
      await AppCenterCrashes.trackException(
        message: details.exception.toString(),
        type: details.exception.runtimeType,
        stackTrace: details.stack,
      );
    };
    runApp(App());
  }, (Object error, StackTrace stack) {
    if (kReleaseMode) {
      AppCenterCrashes.trackException(message: error.toString(), stackTrace: stack);
    }
  });
}
```

**Comment by lsaudon** [comment]
Thank you, @markst, for your question,

I don't know.

You can try with `generateTestCrash()`, if you get the error in AppCenter (it may take some time).

When I look at the [example code in `very_good_core`](https://github.com/VeryGoodOpenSource/very_good_core/blob/main/src/my_app/lib/bootstrap.dart), `FlutterError.onError` is not in `runZonedGuarded`.

**Comment by frederikstonge** [comment]
From this post, it seems to be different. One is for synchronous and one for asynchronous exceptions.

https://github.com/flutter/flutter/issues/97516#issuecomment-1025754820

**Comment by lsaudon** [comment]
Thank you, @frederikstonge, for the details.
I hope his answer helps you @markst. If it doesn't, you can reopen the issue.
